version: '3.8'


services:
  # authorization:
  #   build:
  #     context: ./authorization-service
  #     dockerfile: authorization-service.dockerfile
  #   env_file:
  #     - "./authorization-service/.env"
  #   volumes:
  #     - ./authorization-service:/app
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     -ommand: sudo su postgres "8080:80"
  #   networks:
  #     - local

  films:
    build: ./films
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./films/:/films/
    ports:
      - 8000:8000
    env_file:
      - ./films/.env
  broker:
    build:
      context: ./broker
      dockerfile: broker-service.dockerfile
    env_file:
      - "./broker/.env"
    volumes:
      - ./broker:/app
    ports:
      - "8080:80"
    networks:
      - local
    depends_on:
      - authorization

  authorization:
    container_name: auth
    build:
      context: ./authorization-service
      dockerfile: authorization-service.dockerfile
    env_file:
      - "./authorization-service/.env"
    volumes:
      - ./authorization-service:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - local

  postgres:
    container_name: "pg-db"
    image: postgres
    user: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 60s
      retries: 5
    environment:
      POSTGRES_DB: cinema
      POSTGRES_PASSWORD: "123456"
    networks:
      - local
    volumes:
      - postgres_data:/var/lib/postgresql/data/

networks:
  local:
    driver: bridge

volumes:
  postgres_data: